  GNU nano 6.2                                                                                                      New Buffer *                                                                                                              
# This GitHub Action creates the dinghy digest and publishes them every day.

name: "Weekly activity digests"

on:
  push:
  schedule:
    # 14:50 UTC each Wednesday  
    # https://crontab.guru/#02_13_*_*_*
    - cron: "14 50 * * 3"
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  digest:
    name: "Daily digest"
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install dinghy"
        run: |
          python -m pip install dinghy
      - name: "Run dinghy"
        env:
          # A personal access token with public_repo permission.
          GITHUB_TOKEN: ${{ secrets.DINGHY_ACCESS_TOKEN }}
        run: |
          python -m dinghy
      - name: "Setup Pages"
        uses: actions/configure-pages@v1

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'

      - name: "Deploy to GitHub Pages"
        uses: actions/deploy-pages@v1

